<?php

namespace SaharBundle\Repository;

/**
 * ExamcorigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamcorigRepository extends \Doctrine\ORM\EntityRepository
{
}
