<?php

namespace UtilisateursBundle\Repository;

/**
 * professorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class professorRepository extends \Doctrine\ORM\EntityRepository
{
}
