<?php

namespace MailBundle\Repository;

/**
 * mailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class mailRepository extends \Doctrine\ORM\EntityRepository
{
}
