<?php

namespace BlocBundle\Repository;

/**
 * EtagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtagesRepository extends \Doctrine\ORM\EntityRepository
{
}
