<?php

namespace NotesExamensSeancesBundle\Repository;

/**
 * OsmsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OsmsRepository extends \Doctrine\ORM\EntityRepository
{
}
