<?php

namespace GestionNiveauxBundle\Repository;

/**
 * classeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class matiereRepository extends \Doctrine\ORM\EntityRepository
{
}
